# Generated by Django 5.0.3 on 2024-04-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_item',
            new_name='Inventory',
        ),
    ]
